name: consciousmedia
description: "A new Flutter project."
publish_to: 'none' # pub.dev'e yayınlamak istemiyorsanız bu satırı koruyun.

version: 1.0.0+1

environment:
  # Dart SDK sürümünü güncel Flutter sürümleriyle uyumlu bir aralığa güncelledik.
  # Flutter sürümünüze göre bu aralığı daraltabilir veya genişletebilirsiniz.
  # Örneğin, Flutter 3.22.x, Dart 3.4.x kullanır.
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase bağımlılıklarınız. Hata mesajlarına göre Kotlin sorunu bunlarla ilgiliydi.
  # Gradle güncellemeleri bu sorunu çözmeli. Eğer bu sürümlerle ilgili
  # 'flutter pub get' hatası alırsanız, güncel kararlı sürümleri kontrol edin.
  firebase_core: ^3.13.0 # Bu sürüm standart FlutterFire sürümlerinden farklı görünüyor.
  firebase_auth: ^5.5.2 # Bu sürüm standart FlutterFire sürümlerinden farklı görünüyor.

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints sürümünü güncelledik.
  flutter_lints: ^4.0.0 # Veya projenize uygun en son kararlı sürüm.

flutter:
  uses-material-design: true
  # assets, fonts vb. ayarlarınız buraya gelebilir.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf