name: conscious_media
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Dart SDK versiyonu

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

  # Firebase
  firebase_core: ^3.13.0        # Bir önceki hata mesajına göre güncellendi
  firebase_auth: ^5.5.3         # Bir önceki hata mesajındaki versiyon
  firebase_remote_config: ^5.0.0 # UZAKTAN YAPILANDIRMA İÇİN GEREKLİ (veya en son sürüm)
  # cloud_firestore: ^5.0.2     # Eğer Firestore kullanıyorsanız bu satırın yorumunu kaldırın

  # UI & Icons
  cupertino_icons: ^1.0.2
  # font_awesome_flutter: ^10.1.0 # Eğer kullanıyorsanız bu satırın yorumunu kaldırın
  # fl_chart: ^0.40.0             # Eğer kullanıyorsanız bu satırın yorumunu kaldırın


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets, fonts vb. ayarlarınız buraya gelebilir.
  # assets:
  #   - assets/images/ # Eğer assets klasörünüz varsa bu şekilde tanımlayın